config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  Sidekiq::Web.use(Rack::Auth::Basic) do |username, password|
    username == ENV["SIDEKIQ_WEB_USERNAME"] &&
    password == ENV["SIDEKIQ_WEB_PASSWORD"]
  end
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      get '/cases', to: 'cases#cases'

      namespace :cases do
        get '/earth', to: 'earth#index'
        get '/countries', to: 'countries#index'
        get '/states', to: 'states#index'
        get '/counties', to: 'counties#index'
      end

      scope "/charts" do
        get '/cases', to: 'charts#cases', as: 'charts_cases'
      end
    end
  end

  get '/counties', to: 'page#counties'
  get '/united-states', to: 'page#states'
  get '/earth', to: 'page#earth'
  get '/api', to: 'page#api'

  root 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Florida COVID-19 Cases</title>
    <meta name="description" content="Florida's Positive Cases of COVID-19">

    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_url("apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= image_url("favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= image_url("favicon-16x16.png") %>">

    <meta property="og:type" content="website" />
    <meta property="og:title" content="Florida COVID-19 Cases" />
    <meta property="og:description" content="Florida's Positive Cases of COVID-19" />
    <meta property="og:image" content="<%= image_url("og_tag.png") %>" />
    <meta property="og:url" content="https://floridacovid.com" />

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Florida COVID-19 Cases">
    <meta name="twitter:description" content="Florida's Positive Cases of COVID-19">
    <meta name="twitter:image" content="<%= image_url("og_tag.png") %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-71796222-12"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-71796222-12');
    </script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to "Florida COVID-19", root_url, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", root_url, class: "nav-link #{'active' if current_page?(root_url)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Counties", counties_path, class: "nav-link #{'active' if current_page?(counties_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "United States", united_states_path, class: "nav-link #{'active' if current_page?(united_states_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Earth", earth_path, class: "nav-link #{'active' if current_page?(earth_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "API", api_path, class: "nav-link #{'active' if current_page?(api_path)}" %>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <%= yield %>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">Grab The Code From <a href="https://github.com/arubinofaux/floridacovid" target="_blank">Github</a></p>
      </footer>
    </main>
  </body>
</html>